### ISSUE TITLE
Possible bug in SetBuildVersion because it is adding +[number]

### ISSUE THREAD

**Issue by GeertvanHorrik** [ParticularLabs/GitVersion#202] opened 2014-07-02 09:56 UTC
Found in discussion: https://github.com/Particular/GitVersion/issues/201

Question: what does "0.2.0-unstable.10+10" mean?

It's the result of SetBuildVersion call. When I debug with this url:

/url https://github.com/Orcomp/C5Intervals /b develop /output buildserver

Caused by a call to semanticVersion.ToString("f")

According to @JakeGinnivan , it might be a bug.

**Comment by JakeGinnivan** [comment] 2015-02-15 10:34
This is by design looking into it. Closing this, can reopen another issue down the track if need be to discuss

**Closed by JakeGinnivan** 2015-02-15 10:34 UTC
